### PR TITLE
4-2-stable

### PR DESCRIPTION
**Pull request by meleyal**
Replaces #478, **this is intended for a new branch `4-2-stable`**

### CODE REVIEW

**Comment by meleyal** [comment]
Bump

Just to clarify: This branch is based on `typus:4-0-stable` and includes fixes for Rails 4.2.

The idea is to create a new branch `typus:4-2-stable` based off this pull request.

(The current `typus:4-2-stable` branch was created off of `typus:master` and should be replaced with this pull request).

**Comment by fesplugas** [comment]
`4-2-stable` is now a branch created from `4-0-stable`.

**Comment by fesplugas** [comment]
image

**Comment by fesplugas** [comment]
Can you open a new PR witht the destination set to 4-2-stable?

**Comment by meleyal** [comment]
replaced by #483

**Comment by baban** [comment]
Oh...Sorry...
I'm fixing now...

**Pull request closed without merging**
