### PR TITLE
remove old scss file leftover from bootstrap gem

### PR DESCRIPTION
**Pull request by meleyal**

### CODE REVIEW

**Comment by fesplugas** [comment]
Do we want to be able to override some settings?

**Comment by meleyal** [comment]
Right now that wouldn't be possible as the bootstrap.css is already compiled

**Comment by fesplugas** [comment]
And the signing form?

**Comment by meleyal** [comment]
Sorry I misunderstood. Yes we want to include the overrides and the signin form.

This commit is just to remove `.scss` file which was left over from using the bootstrap-sass gem, we still have the `.css` file which includes the typus stuff:
https://github.com/typus/typus/blob/master/app/assets/stylesheets/typus/application.css

**Comment by meleyal** [comment]
Bump

**Pull request merged**
